apiVersion: v1
kind: Service
metadata:
  name: {{ include "jmgl.fullname" . }}-api
  labels: {{- include "jmgl.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector: {{- include "jmgl.selector" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
