apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jmgl.fullname" . }}-api
  labels: {{- include "jmgl.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.api.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
