{{- if and .Values.api.secret.create (not .Values.api.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jmgl.secretName" . }}
  labels: {{- include "jmgl.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.api.secret.values }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
